# First Blueprint Attempt

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, TimeDistributed 
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

In [2]:
features = np.array([
    [1., 0.], 
    [0.9, 0.1], 
    [0.8, 0.2], 
    [0.2, 0.0], 
    [0.1, 0.5], 
    [0., 0.6], 
    [0.1, 0.8],
    [0.1, 0.9]
])

test_features = np.array([
    [1., 0.], 
    [0.8, 0.2], 
    [0.7, 0.3], 
    [0.3, 0.0] 
])    

# we begin to count at the 4th element because we look at sequences of 4 steps... 
targets = np.array([
    [0., 1.], 
    [0., 0.9], 
    [0., 0.8], 
    [0., 0.3], 
    [0.1, 0.], 
    [0.4, 0.], 
    [0.8, 0.],
    [1., 0.]    
])

print(features.shape[0])

#features_length = features.shape[0]

#features = features.reshape(1, features.shape[0], INPUT_DIM)
#targets = targets.reshape(1, targets.shape[0], OUTPUT_DIM)
#print(features.shape)

#print(features)

8


In [3]:
def rolling_window2D(a,n):
    # a: 2D Input array 
    # n: Group/sliding window length
    return a[np.arange(a.shape[0]-n+1)[:,None] + np.arange(n)]

In [4]:
features = rolling_window2D(features,4)
print(features)

[[[1.  0. ]
  [0.9 0.1]
  [0.8 0.2]
  [0.2 0. ]]

 [[0.9 0.1]
  [0.8 0.2]
  [0.2 0. ]
  [0.1 0.5]]

 [[0.8 0.2]
  [0.2 0. ]
  [0.1 0.5]
  [0.  0.6]]

 [[0.2 0. ]
  [0.1 0.5]
  [0.  0.6]
  [0.1 0.8]]

 [[0.1 0.5]
  [0.  0.6]
  [0.1 0.8]
  [0.1 0.9]]]


In [5]:
test_features = test_features.reshape(1, 4, 2)
print(test_features)

[[[1.  0. ]
  [0.8 0.2]
  [0.7 0.3]
  [0.3 0. ]]]


In [6]:
# we only have 4 x single batches of sequences and we only want to predict
targets = targets[3:]
print(targets)

[[0.  0.3]
 [0.1 0. ]
 [0.4 0. ]
 [0.8 0. ]
 [1.  0. ]]


In [7]:
output_units = 2
batch_size = 1
time_steps = 4
number_of_features = 2
epochs = 20

model = Sequential()
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=False))
model.add(Dense(units=output_units, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='mse')
model.fit(x=features,y=targets, batch_size=batch_size,  epochs=epochs)




2022-05-16 12:13:59.245880: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Epoch 1/20
5/5 [==============================] - 1s 3ms/step - loss: 0.1712
Epoch 2/20
5/5 [==============================] - 0s 3ms/step - loss: 0.1300
Epoch 3/20
5/5 [==============================] - 0s 4ms/step - loss: 0.1044
Epoch 4/20
5/5 [==============================] - 0s 4ms/step - loss: 0.1012
Epoch 5/20
5/5 [==============================] - 0s 4ms/step - loss: 0.0928
Epoch 6/20
5/5 [==============================] - 0s 4ms/step - loss: 0.0859
Epoch 7/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0790
Epoch 8/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0810
Epoch 9/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0749
Epoch 10/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0754
Epoch 11/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0674
Epoch 12/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0659
Epoch 13/20
5/5 [==============================] - 0s 3ms/step - loss: 0.

In [8]:
model.predict(test_features)

array([[0.28382984, 0.09385237]], dtype=float32)

# Run with valid training-data

In [9]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

### Meta Params

In [10]:
output_units = 2
batch_size = 1
time_steps = 4
number_of_features = 2
epochs = 1

### Load Dataset

In [114]:
file_name = '220511_104521_Birk-Test-Data_60hz_cl.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32')
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
features, targets = values[:,:-output_units], values[:,number_of_features:]
print('training_input shape: ', features.shape, 'training_output shape: ', targets.shape)

Loading Trainingsdata from File: 220511_104521_Birk-Test-Data_60hz_cl.txt   ...
Trainingsdata points:  1800 

training_input shape:  (1800, 2) training_output shape:  (1800, 2)


### Transform Dataset

In [115]:
def rolling_window2D(a,n):
    # a: 2D Input array 
    # n: Group/sliding window length
    return a[np.arange(a.shape[0]-n+1)[:,None] + np.arange(n)]

In [116]:
features = rolling_window2D(features,time_steps)


In [117]:
# we only have 4 x single batches of sequences and we only want to predict
targets = targets[time_steps-1:]
print(targets)

[[0.02924183 0.9707582 ]
 [0.02924183 0.9707582 ]
 [0.02924183 0.9707582 ]
 ...
 [0.8945754  0.10542458]
 [0.8945754  0.10542458]
 [0.8945754  0.10542458]]


### Build LSTM Model

In [133]:
model = Sequential()
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=True))
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=False))

model.add(Dense(units=output_units, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='mse')


### Train

In [134]:
model.fit(x=features,y=targets, batch_size=batch_size,  epochs=epochs)

1797/1797 [==============================] - 8s 3ms/step - loss: 0.0051


### Predict Values

In [139]:
test_features = np.array([
    [-0.5, 0.], 
    [-0.6, 0.1], 
    [-0.5, 0.2], 
    [-0.6, 0.1], 
])    

test_features = test_features.reshape(1, 4, 2)
#print(test_features)
model.predict(test_features)

array([[0.7910385 , 0.20813364]], dtype=float32)

In [138]:
test_features = np.array([
    [0., -0.6], 
    [0.1, -0.5], 
    [0.2, -0.4], 
    [0.1, -0.6], 
])    

test_features = test_features.reshape(1, 4, 2)
model.predict(test_features)
#print(test_features)

array([[0.04859897, 0.95059055]], dtype=float32)

# Dynamic Features and Outputs

In [78]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

output_units = 8
batch_size = 1
time_steps = 300
number_of_features = 85
epochs = 1

In [79]:
file_name = '220512_104848_All-Parameters_normalized_60hz.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32', skiprows=1)
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
features, targets = values[:,:-output_units], values[:,number_of_features:]
print('training_input shape: ', features.shape, 'training_output shape: ', targets.shape)

Loading Trainingsdata from File: 220512_104848_All-Parameters_normalized_60hz.txt   ...
Trainingsdata points:  337 

training_input shape:  (337, 85) training_output shape:  (337, 8)


In [80]:
def rolling_window2D(a,n):
    # a: 2D Input array 
    # n: Group/sliding window length
    return a[np.arange(a.shape[0]-n+1)[:,None] + np.arange(n)]

features = rolling_window2D(features,time_steps)
print(features.shape)

(38, 300, 85)


In [81]:
targets = targets[time_steps-1:]
print(targets)

[[0.2061075  0.3454916  0.5000001  0.6545086  0.7938927  0.9045086
  0.9755283  1.        ]
 [0.3454916  0.5000001  0.6545086  0.7938927  0.9045086  0.9755283
  1.         0.9755282 ]
 [0.5000001  0.6545086  0.7938927  0.9045086  0.9755283  1.
  0.9755282  0.9045085 ]
 [0.6545086  0.7938927  0.9045086  0.9755283  1.         0.9755282
  0.9045084  0.7938926 ]
 [0.7938927  0.9045086  0.9755283  1.         0.9755282  0.9045085
  0.7938925  0.6545084 ]
 [0.9045086  0.9755283  1.         0.9755282  0.9045085  0.7938925
  0.6545084  0.4999999 ]
 [0.9755283  1.         0.9755282  0.9045084  0.7938925  0.6545084
  0.4999999  0.3454914 ]
 [1.         0.9755282  0.9045085  0.7938925  0.6545084  0.4999999
  0.3454913  0.2061073 ]
 [0.9890738  0.9330126  0.8345652  0.7033682  0.5522641  0.396044
  0.2499999  0.1284275 ]
 [0.9330127  0.8345652  0.7033682  0.5522641  0.396044   0.2499999
  0.1284275  0.04322723]
 [0.7938925  0.6545084  0.4999999  0.3454914  0.2061073  0.09549144
  0.0244717  0.     

In [82]:
model = Sequential()
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=True))
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=False))
model.add(Dense(units=output_units, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='mse')

In [83]:
model.fit(x=features,y=targets, batch_size=batch_size,  epochs=epochs)

38/38 [==============================] - 6s 88ms/step - loss: 0.0845


In [92]:
model.predict(features[0:1])

array([[0.41810498, 0.5685426 , 0.6611764 , 0.7974617 , 0.82163703,
        0.8676672 , 0.854517  , 0.8359066 ]], dtype=float32)

In [94]:
model.predict(features[1:2])

array([[0.546056  , 0.67388827, 0.7351044 , 0.8373897 , 0.83446884,
        0.85514235, 0.8152429 , 0.77438533]], dtype=float32)

# Reformat Prediction Input

In [342]:
features[2:3].shape

(1, 8, 85)

In [343]:
test_features = np.array([
        [0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 ,
         0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 ,
         0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 ,
         0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 ,
         0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 ,
         0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 ,
         0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9567732 ,
         0.8715731 , 0.7500009 , 0.6039568 , 0.9567732 , 0.8715731 ,
         0.7500009 , 0.6039568 , 0.9567732 , 0.8715731 , 0.7500009 ,
         0.6039568 , 0.9567732 , 0.8715731 , 0.7500009 , 0.6039568 ,
         0.9567732 , 0.8715731 , 0.7500009 , 0.6039568 , 0.9567732 ,
         0.8715731 , 0.7500009 , 0.6039568 , 0.4477368 , 0.2966326 ,
         0.1654355 , 0.06698781, 0.01092643, 0.00273895, 0.04322687],
        [0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 ,
         0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 ,
         0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 ,
         0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 ,
         0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 ,
         0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 ,
         0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.9045091 ,
         0.7938935 , 0.6545095 , 0.500001  , 0.9045091 , 0.7938935 ,
         0.6545095 , 0.500001  , 0.9045091 , 0.7938935 , 0.6545095 ,
         0.500001  , 0.9045091 , 0.7938935 , 0.6545095 , 0.500001  ,
         0.9045091 , 0.7938935 , 0.6545095 , 0.500001  , 0.9045091 ,
         0.7938935 , 0.6545095 , 0.500001  , 0.3454925 , 0.2061082 ,
         0.09549212, 0.02447206, 0.        , 0.02447143, 0.0954909 ],
        [0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 ,
         0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 ,
         0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 ,
         0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 ,
         0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 ,
         0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 ,
         0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7938935 ,
         0.6545095 , 0.500001  , 0.3454925 , 0.7938935 , 0.6545095 ,
         0.500001  , 0.3454925 , 0.7938935 , 0.6545095 , 0.500001  ,
         0.3454925 , 0.7938935 , 0.6545095 , 0.500001  , 0.3454925 ,
         0.7938935 , 0.6545095 , 0.500001  , 0.3454925 , 0.7938935 ,
         0.6545095 , 0.500001  , 0.3454925 , 0.2061082 , 0.09549212,
         0.02447206, 0.        , 0.02447143, 0.09549087, 0.2061065 ],
        [0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 ,
         0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 ,
         0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 ,
         0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 ,
         0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 ,
         0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 ,
         0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.6545095 ,
         0.5000011 , 0.3454925 , 0.2061082 , 0.6545095 , 0.5000011 ,
         0.3454925 , 0.2061082 , 0.6545095 , 0.5000011 , 0.3454925 ,
         0.2061082 , 0.6545095 , 0.5000011 , 0.3454925 , 0.2061082 ,
         0.6545095 , 0.5000011 , 0.3454925 , 0.2061082 , 0.6545095 ,
         0.5000011 , 0.3454925 , 0.2061082 , 0.09549212, 0.02447206,
         0.        , 0.02447143, 0.0954909 , 0.2061065 , 0.3454905 ],
        [0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 ,
         0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 ,
         0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 ,
         0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 ,
         0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 ,
         0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 ,
         0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.5000011 ,
         0.3454925 , 0.2061082 , 0.09549209, 0.5000011 , 0.3454925 ,
         0.2061082 , 0.09549209, 0.5000011 , 0.3454925 , 0.2061082 ,
         0.09549209, 0.5000011 , 0.3454925 , 0.2061082 , 0.09549209,
         0.5000011 , 0.3454925 , 0.2061082 , 0.09549209, 0.5000011 ,
         0.3454925 , 0.2061082 , 0.09549209, 0.02447206, 0.        ,
         0.02447143, 0.0954909 , 0.2061065 , 0.3454905 , 0.499999  ],
        [0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.2499991 ,
         0.1284269 , 0.04322684, 0.2499991 , 0.1284269 , 0.04322684,
         0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.2499991 ,
         0.1284269 , 0.04322684, 0.2499991 , 0.1284269 , 0.04322684,
         0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.2499991 ,
         0.1284269 , 0.04322684, 0.2499991 , 0.1284269 , 0.04322684,
         0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.3454925 ,
         0.2061082 , 0.09549212, 0.02447206, 0.3454925 , 0.2061082 ,
         0.09549212, 0.02447206, 0.3454925 , 0.2061082 , 0.09549212,
         0.02447206, 0.3454925 , 0.2061082 , 0.09549212, 0.02447206,
         0.3454925 , 0.2061082 , 0.09549212, 0.02447206, 0.3454925 ,
         0.2061082 , 0.09549212, 0.02447206, 0.        , 0.02447143,
         0.0954909 , 0.2061065 , 0.3454905 , 0.499999  , 0.6545075 ],
        [0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.1654339 ,
         0.06698677, 0.01092598, 0.1654339 , 0.06698677, 0.01092598,
         0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.1654339 ,
         0.06698677, 0.01092598, 0.1654339 , 0.06698677, 0.01092598,
         0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.1654339 ,
         0.06698677, 0.01092598, 0.1654339 , 0.06698677, 0.01092598,
         0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.2500009 ,
         0.1284283 , 0.0432277 , 0.00273916, 0.2500009 , 0.1284283 ,
         0.0432277 , 0.00273916, 0.2500009 , 0.1284283 , 0.0432277 ,
         0.00273916, 0.2500009 , 0.1284283 , 0.0432277 , 0.00273916,
         0.2500009 , 0.1284283 , 0.0432277 , 0.00273916, 0.2500009 ,
         0.1284283 , 0.0432277 , 0.00273916, 0.01092598, 0.06698677,
         0.1654339 , 0.2966307 , 0.4477347 , 0.6039548 , 0.7499991 ],
        [0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.06698677,
         0.01092598, 0.00273916, 0.06698677, 0.01092598, 0.00273916,
         0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.06698677,
         0.01092598, 0.00273916, 0.06698677, 0.01092598, 0.00273916,
         0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.06698677,
         0.01092598, 0.00273916, 0.06698677, 0.01092598, 0.00273916,
         0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.1284283 ,
         0.0432277 , 0.00273916, 0.01092598, 0.1284283 , 0.0432277 ,
         0.00273916, 0.01092598, 0.1284283 , 0.0432277 , 0.00273916,
         0.01092598, 0.1284283 , 0.0432277 , 0.00273916, 0.01092598,
         0.1284283 , 0.0432277 , 0.00273916, 0.01092598, 0.1284283 ,
         0.0432277 , 0.00273916, 0.01092598, 0.06698677, 0.1654339 ,
         0.2966307 , 0.4477347 , 0.6039549 , 0.7499991 , 0.8715718 ]
])

### Add a dimension to fit out prediciton model

In [344]:
print(test_features.shape)
test_features = np.expand_dims(test_features, axis=0)
print(test_features.shape)

(8, 85)
(1, 8, 85)


In [346]:
model.predict(test_features)

array([[0.1553083 , 0.12842205, 0.11520863, 0.12580898, 0.17699072,
        0.22466499, 0.32627314, 0.4448668 ]], dtype=float32)