# First Blueprint Attempt

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

In [2]:
features = np.array([
    [1., 0.], 
    [1., 0.], 
    [0., 1.], 
    [0., 1.], 
    [1., 0.], 
    [1., 0.], 
    [0., 1.]
])

targets = np.array([
    [0., 1.], 
    [0., 1.], 
    [1., 0.], 
    [1., 0.], 
    [0., 1.], 
    [0., 1.], 
    [1., 0.]
])

In [3]:
INPUT_DIM = 2
OUTPUT_DIM = 2
HIDDEN1_DIM = 128
LEARNING_RATE = 2

model = Sequential()

my_init=keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=None)
model.add(Dense(HIDDEN1_DIM, activation='sigmoid', input_dim=INPUT_DIM, kernel_initializer=my_init, bias_initializer=my_init))
model.add(Dense(OUTPUT_DIM, activation='sigmoid',kernel_initializer=my_init, bias_initializer=my_init))
sgd = SGD(lr=LEARNING_RATE, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

INITIAL_EPOCHS = 500
BATCH_SIZE = 1

model.fit(features, targets, epochs=INITIAL_EPOCHS, batch_size=BATCH_SIZE, shuffle=True)
model.summary()
print('Initial training finished...')

Epoch 1/500


2022-05-11 13:20:23.682547: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/opt/anaconda3/envs/smart/lib/python3.7/site-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


7/7 [==============================] - 0s 1ms/step - loss: 9.8013 - accuracy: 0.5714
Epoch 2/500
7/7 [==============================] - 0s 1ms/step - loss: 1.1008 - accuracy: 0.5714
Epoch 3/500
7/7 [==============================] - 0s 1ms/step - loss: 1.1302 - accuracy: 0.1429
Epoch 4/500
7/7 [==============================] - 0s 1ms/step - loss: 1.2078 - accuracy: 0.4286
Epoch 5/500
7/7 [==============================] - 0s 1ms/step - loss: 1.1030 - accuracy: 0.4286
Epoch 6/500
7/7 [==============================] - 0s 1ms/step - loss: 0.7924 - accuracy: 0.7143
Epoch 7/500
7/7 [==============================] - 0s 1ms/step - loss: 1.3924 - accuracy: 0.4286
Epoch 8/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4122 - accuracy: 0.2857
Epoch 9/500
7/7 [==============================] - 0s 1ms/step - loss: 1.0051 - accuracy: 0.4286
Epoch 10/500
7/7 [==============================] - 0s 1ms/step - loss: 0.8916 - accuracy: 0.2857
Epoch 11/500
7/7 [=======================

7/7 [==============================] - 0s 1ms/step - loss: 8.0911e-04 - accuracy: 1.0000
Epoch 85/500
7/7 [==============================] - 0s 1ms/step - loss: 7.9982e-04 - accuracy: 1.0000
Epoch 86/500
7/7 [==============================] - 0s 1ms/step - loss: 7.9071e-04 - accuracy: 1.0000
Epoch 87/500
7/7 [==============================] - 0s 995us/step - loss: 7.8335e-04 - accuracy: 1.0000
Epoch 88/500
7/7 [==============================] - 0s 1ms/step - loss: 7.7385e-04 - accuracy: 1.0000
Epoch 89/500
7/7 [==============================] - 0s 1ms/step - loss: 7.6555e-04 - accuracy: 1.0000
Epoch 90/500
7/7 [==============================] - 0s 1ms/step - loss: 7.5688e-04 - accuracy: 1.0000
Epoch 91/500
7/7 [==============================] - 0s 1ms/step - loss: 7.4876e-04 - accuracy: 1.0000
Epoch 92/500
7/7 [==============================] - 0s 979us/step - loss: 7.4096e-04 - accuracy: 1.0000
Epoch 93/500
7/7 [==============================] - 0s 1ms/step - loss: 7.3338e-04 - accura

7/7 [==============================] - 0s 1ms/step - loss: 4.2489e-04 - accuracy: 1.0000
Epoch 164/500
7/7 [==============================] - 0s 1ms/step - loss: 4.2235e-04 - accuracy: 1.0000
Epoch 165/500
7/7 [==============================] - 0s 1ms/step - loss: 4.1977e-04 - accuracy: 1.0000
Epoch 166/500
7/7 [==============================] - 0s 1ms/step - loss: 4.1740e-04 - accuracy: 1.0000
Epoch 167/500
7/7 [==============================] - 0s 1ms/step - loss: 4.1481e-04 - accuracy: 1.0000
Epoch 168/500
7/7 [==============================] - 0s 1ms/step - loss: 4.1253e-04 - accuracy: 1.0000
Epoch 169/500
7/7 [==============================] - 0s 1ms/step - loss: 4.1002e-04 - accuracy: 1.0000
Epoch 170/500
7/7 [==============================] - 0s 1ms/step - loss: 4.0770e-04 - accuracy: 1.0000
Epoch 171/500
7/7 [==============================] - 0s 1ms/step - loss: 4.0540e-04 - accuracy: 1.0000
Epoch 172/500
7/7 [==============================] - 0s 1ms/step - loss: 4.0311e-04 - a

7/7 [==============================] - 0s 1ms/step - loss: 2.8854e-04 - accuracy: 1.0000
Epoch 243/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8731e-04 - accuracy: 1.0000
Epoch 244/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8620e-04 - accuracy: 1.0000
Epoch 245/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8499e-04 - accuracy: 1.0000
Epoch 246/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8388e-04 - accuracy: 1.0000
Epoch 247/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8283e-04 - accuracy: 1.0000
Epoch 248/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8167e-04 - accuracy: 1.0000
Epoch 249/500
7/7 [==============================] - 0s 1ms/step - loss: 2.8053e-04 - accuracy: 1.0000
Epoch 250/500
7/7 [==============================] - 0s 1ms/step - loss: 2.7949e-04 - accuracy: 1.0000
Epoch 251/500
7/7 [==============================] - 0s 985us/step - loss: 2.7832e-04 -

7/7 [==============================] - 0s 1ms/step - loss: 2.1858e-04 - accuracy: 1.0000
Epoch 322/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1788e-04 - accuracy: 1.0000
Epoch 323/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1723e-04 - accuracy: 1.0000
Epoch 324/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1653e-04 - accuracy: 1.0000
Epoch 325/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1589e-04 - accuracy: 1.0000
Epoch 326/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1525e-04 - accuracy: 1.0000
Epoch 327/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1458e-04 - accuracy: 1.0000
Epoch 328/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1395e-04 - accuracy: 1.0000
Epoch 329/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1336e-04 - accuracy: 1.0000
Epoch 330/500
7/7 [==============================] - 0s 1ms/step - loss: 2.1277e-04 - a

7/7 [==============================] - 0s 1ms/step - loss: 1.7595e-04 - accuracy: 1.0000
Epoch 401/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7552e-04 - accuracy: 1.0000
Epoch 402/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7507e-04 - accuracy: 1.0000
Epoch 403/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7464e-04 - accuracy: 1.0000
Epoch 404/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7421e-04 - accuracy: 1.0000
Epoch 405/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7382e-04 - accuracy: 1.0000
Epoch 406/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7341e-04 - accuracy: 1.0000
Epoch 407/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7297e-04 - accuracy: 1.0000
Epoch 408/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7258e-04 - accuracy: 1.0000
Epoch 409/500
7/7 [==============================] - 0s 1ms/step - loss: 1.7213e-04 - a

7/7 [==============================] - 0s 1ms/step - loss: 1.4728e-04 - accuracy: 1.0000
Epoch 480/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4697e-04 - accuracy: 1.0000
Epoch 481/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4667e-04 - accuracy: 1.0000
Epoch 482/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4638e-04 - accuracy: 1.0000
Epoch 483/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4607e-04 - accuracy: 1.0000
Epoch 484/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4578e-04 - accuracy: 1.0000
Epoch 485/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4549e-04 - accuracy: 1.0000
Epoch 486/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4518e-04 - accuracy: 1.0000
Epoch 487/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4489e-04 - accuracy: 1.0000
Epoch 488/500
7/7 [==============================] - 0s 1ms/step - loss: 1.4461e-04 - a

In [4]:
features_test = np.array([
    [0., 1.]
])


model.predict(features_test)

array([[9.9980253e-01, 1.9735098e-04]], dtype=float32)

In [5]:
model.predict(np.array([[1., 0.]]))

array([[9.871202e-05, 9.999013e-01]], dtype=float32)

# Testing Data Structure

In [6]:
file_name = '220511_104521_Birk-Test-Data_60hz_cl.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32')
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
training_input, training_output = values[:,:-OUTPUT_DIM], values[:,INPUT_DIM:]
print('training_input shape: ', training_input.shape, 'training_output shape: ', training_output.shape)

Loading Trainingsdata from File: 220511_104521_Birk-Test-Data_60hz_cl.txt   ...
Trainingsdata points:  1800 

training_input shape:  (1800, 2) training_output shape:  (1800, 2)


In [7]:
values.shape[0]

1800

In [8]:
values[:,:-OUTPUT_DIM]

array([[ 0.265404, -0.502501],
       [ 0.265404, -0.502501],
       [ 0.265404, -0.502501],
       ...,
       [-0.671844,  0.330793],
       [-0.671844,  0.330793],
       [-0.671844,  0.330793]], dtype=float32)

In [9]:
values[:,INPUT_DIM:]

array([[0.02924183, 0.9707582 ],
       [0.02924183, 0.9707582 ],
       [0.02924183, 0.9707582 ],
       ...,
       [0.8945754 , 0.10542458],
       [0.8945754 , 0.10542458],
       [0.8945754 , 0.10542458]], dtype=float32)

# Run with valid training-data

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

### Meta Params

In [11]:
INPUT_DIM = 2
OUTPUT_DIM = 2
HIDDEN1_DIM = 128
LEARNING_RATE = 3

EPOCHS = 100
BATCH_SIZE = 500

### Load Dataset

In [12]:
file_name = '220511_104521_Birk-Test-Data_60hz_cl.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32')
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
features, targets = values[:,:-OUTPUT_DIM], values[:,INPUT_DIM:]
print('training_input shape: ', features.shape, 'training_output shape: ', targets.shape)

Loading Trainingsdata from File: 220511_104521_Birk-Test-Data_60hz_cl.txt   ...
Trainingsdata points:  1800 

training_input shape:  (1800, 2) training_output shape:  (1800, 2)


### Build Linear Regression Model

In [13]:
model = Sequential()

my_init=keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=None)
model.add(Dense(HIDDEN1_DIM, activation='sigmoid', input_dim=INPUT_DIM, kernel_initializer=my_init, bias_initializer=my_init))
model.add(Dense(OUTPUT_DIM, activation='sigmoid',kernel_initializer=my_init, bias_initializer=my_init))
sgd = SGD(lr=LEARNING_RATE, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])


### Train

In [14]:
model.fit(features, targets, epochs=EPOCHS, batch_size=BATCH_SIZE, shuffle=True)
model.summary()
print('Initial training finished...')

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 4.7864 - accuracy: 0.4933
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 3.2120 - accuracy: 0.5817
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3812 - accuracy: 0.8689
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2688 - accuracy: 0.9956
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2798 - accuracy: 0.9956
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2644 - accuracy: 0.9956
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2554 - accuracy: 0.9956
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2534 - accuracy: 0.9956
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2534 - accuracy: 0.9956
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2539 - accuracy: 0.9956
Epoch 11/100
4/4 [===========

4/4 [==============================] - 0s 2ms/step - loss: 0.2514 - accuracy: 0.9956
Epoch 85/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2514 - accuracy: 0.9956
Epoch 86/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 87/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 88/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 89/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 90/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 91/100
4/4 [==============================] - 0s 1ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 92/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 93/100
4/4 [==============================] - 0s 1ms/step - loss: 0.2513 - accuracy: 0.9956
Epoch 94/100
4/4 [===============

### Predict Values

In [18]:
model.predict(np.array([[-0.6, 0.3]]))

array([[0.8773707 , 0.12261981]], dtype=float32)