# First Blueprint Attempt

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, TimeDistributed 
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

In [297]:
features = np.array([
    [1., 0.], 
    [0.9, 0.1], 
    [0.8, 0.2], 
    [0.2, 0.0], 
    [0.1, 0.5], 
    [0., 0.6], 
    [0.1, 0.8],
    [0.1, 0.9]
])

test_features = np.array([
    [1., 0.], 
    [0.8, 0.2], 
    [0.7, 0.3], 
    [0.3, 0.0] 
])    

# we begin to count at the 4th element because we look at sequences of 4 steps... 
targets = np.array([
    [0., 1.], 
    [0., 0.9], 
    [0., 0.8], 
    [0., 0.3], 
    [0.1, 0.], 
    [0.4, 0.], 
    [0.8, 0.],
    [1., 0.]    
])

print(features.shape[0])

#features_length = features.shape[0]

#features = features.reshape(1, features.shape[0], INPUT_DIM)
#targets = targets.reshape(1, targets.shape[0], OUTPUT_DIM)
#print(features.shape)

#print(features)

8


In [14]:
def rolling_window2D(a,n):
    # a: 2D Input array 
    # n: Group/sliding window length
    return a[np.arange(a.shape[0]-n+1)[:,None] + np.arange(n)]

In [15]:
features = rolling_window2D(features,4)
print(features)

[[[1.  0. ]
  [0.9 0.1]
  [0.8 0.2]
  [0.2 0. ]]

 [[0.9 0.1]
  [0.8 0.2]
  [0.2 0. ]
  [0.1 0.5]]

 [[0.8 0.2]
  [0.2 0. ]
  [0.1 0.5]
  [0.  0.6]]

 [[0.2 0. ]
  [0.1 0.5]
  [0.  0.6]
  [0.1 0.8]]

 [[0.1 0.5]
  [0.  0.6]
  [0.1 0.8]
  [0.1 0.9]]]


In [16]:
test_features = test_features.reshape(1, 4, 2)
print(test_features)

[[[1.  0. ]
  [0.8 0.2]
  [0.7 0.3]
  [0.3 0. ]]]


In [17]:
# we only have 4 x single batches of sequences and we only want to predict
targets = targets[3:]
print(targets)

[[0.  0.3]
 [0.1 0. ]
 [0.4 0. ]
 [0.8 0. ]
 [1.  0. ]]


In [18]:
output_units = 2
batch_size = 1
time_steps = 4
number_of_features = 2
epochs = 20

model = Sequential()
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=False))
model.add(Dense(units=output_units, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='mse')
model.fit(x=features,y=targets, batch_size=batch_size,  epochs=epochs)




Epoch 1/20
5/5 [==============================] - 1s 3ms/step - loss: 0.1599
Epoch 2/20
5/5 [==============================] - 0s 3ms/step - loss: 0.1106
Epoch 3/20
5/5 [==============================] - 0s 3ms/step - loss: 0.1261
Epoch 4/20
5/5 [==============================] - 0s 3ms/step - loss: 0.1017
Epoch 5/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0903
Epoch 6/20
5/5 [==============================] - 0s 4ms/step - loss: 0.0946
Epoch 7/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0849
Epoch 8/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0839
Epoch 9/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0804
Epoch 10/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0747
Epoch 11/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0782
Epoch 12/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0770
Epoch 13/20
5/5 [==============================] - 0s 3ms/step - loss: 0.

In [19]:
model.predict(test_features)

array([[0.24645644, 0.04081601]], dtype=float32)

# Run with valid training-data

In [112]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

### Meta Params

In [113]:
output_units = 2
batch_size = 1
time_steps = 4
number_of_features = 2
epochs = 1

### Load Dataset

In [114]:
file_name = '220511_104521_Birk-Test-Data_60hz_cl.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32')
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
features, targets = values[:,:-output_units], values[:,number_of_features:]
print('training_input shape: ', features.shape, 'training_output shape: ', targets.shape)

Loading Trainingsdata from File: 220511_104521_Birk-Test-Data_60hz_cl.txt   ...
Trainingsdata points:  1800 

training_input shape:  (1800, 2) training_output shape:  (1800, 2)


### Transform Dataset

In [115]:
def rolling_window2D(a,n):
    # a: 2D Input array 
    # n: Group/sliding window length
    return a[np.arange(a.shape[0]-n+1)[:,None] + np.arange(n)]

In [116]:
features = rolling_window2D(features,time_steps)


In [117]:
# we only have 4 x single batches of sequences and we only want to predict
targets = targets[time_steps-1:]
print(targets)

[[0.02924183 0.9707582 ]
 [0.02924183 0.9707582 ]
 [0.02924183 0.9707582 ]
 ...
 [0.8945754  0.10542458]
 [0.8945754  0.10542458]
 [0.8945754  0.10542458]]


### Build LSTM Model

In [133]:
model = Sequential()
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=True))
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=False))

model.add(Dense(units=output_units, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='mse')


### Train

In [134]:
model.fit(x=features,y=targets, batch_size=batch_size,  epochs=epochs)

1797/1797 [==============================] - 8s 3ms/step - loss: 0.0051


### Predict Values

In [139]:
test_features = np.array([
    [-0.5, 0.], 
    [-0.6, 0.1], 
    [-0.5, 0.2], 
    [-0.6, 0.1], 
])    

test_features = test_features.reshape(1, 4, 2)
#print(test_features)
model.predict(test_features)

array([[0.7910385 , 0.20813364]], dtype=float32)

In [138]:
test_features = np.array([
    [0., -0.6], 
    [0.1, -0.5], 
    [0.2, -0.4], 
    [0.1, -0.6], 
])    

test_features = test_features.reshape(1, 4, 2)
model.predict(test_features)
#print(test_features)

array([[0.04859897, 0.95059055]], dtype=float32)

# Dynamic Features and Outputs

In [31]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import SGD
import keras
import numpy as np

output_units = 8
batch_size = 1
time_steps = 8
number_of_features = 67
epochs = 1

In [32]:
file_name = 'training_file_crashes.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32', skiprows=1)
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
features, targets = values[:,:-output_units], values[:,number_of_features:]
print('training_input shape: ', features.shape, 'training_output shape: ', targets.shape)

Loading Trainingsdata from File: training_file_crashes.txt   ...
Trainingsdata points:  7136 

training_input shape:  (7136, 67) training_output shape:  (7136, 8)


In [33]:
def rolling_window2D(a,n):
    # a: 2D Input array 
    # n: Group/sliding window length
    return a[np.arange(a.shape[0]-n+1)[:,None] + np.arange(n)]

features = rolling_window2D(features,time_steps)
print(features.shape)

(7129, 8, 67)


In [34]:
targets = targets[time_steps-1:]
print(targets.shape)

(7129, 8)


In [35]:
model = Sequential()
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=True))
model.add(LSTM(units=128, batch_input_shape=(batch_size, time_steps, number_of_features), stateful=True, return_sequences=False))
model.add(Dense(units=output_units, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='mse')

In [36]:
model.fit(x=features,y=targets, batch_size=batch_size,  epochs=epochs)

7129/7129 [==============================] - 36s 5ms/step - loss: 0.0361


In [37]:
model.predict(features[0:1])

array([[0.877529  , 0.01209083, 0.00120312, 0.004448  , 0.00117955,
        0.00223258, 0.00155881, 0.01792154]], dtype=float32)

In [38]:
model.predict(features[1:2])

array([[9.4137836e-01, 1.5754580e-02, 8.8590384e-04, 3.3599734e-03,
        1.8724203e-03, 2.1944642e-03, 9.9822879e-04, 9.1899037e-03]],
      dtype=float32)

# Reformat Prediction Input

In [14]:
features[2:3].shape

(1, 8, 85)

In [15]:
test_features = np.array([
        [0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 ,
         0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 ,
         0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 ,
         0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 ,
         0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 ,
         0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 ,
         0.9045079 , 0.7938918 , 0.6545075 , 0.9045079 , 0.7938918 ,
         0.6545075 , 0.9045079 , 0.7938918 , 0.6545075 , 0.9567732 ,
         0.8715731 , 0.7500009 , 0.6039568 , 0.9567732 , 0.8715731 ,
         0.7500009 , 0.6039568 , 0.9567732 , 0.8715731 , 0.7500009 ,
         0.6039568 , 0.9567732 , 0.8715731 , 0.7500009 , 0.6039568 ,
         0.9567732 , 0.8715731 , 0.7500009 , 0.6039568 , 0.9567732 ,
         0.8715731 , 0.7500009 , 0.6039568 , 0.4477368 , 0.2966326 ,
         0.1654355 , 0.06698781, 0.01092643, 0.00273895, 0.04322687],
        [0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 ,
         0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 ,
         0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 ,
         0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 ,
         0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 ,
         0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 ,
         0.8345646 , 0.7033674 , 0.5522632 , 0.8345646 , 0.7033674 ,
         0.5522632 , 0.8345646 , 0.7033674 , 0.5522632 , 0.9045091 ,
         0.7938935 , 0.6545095 , 0.500001  , 0.9045091 , 0.7938935 ,
         0.6545095 , 0.500001  , 0.9045091 , 0.7938935 , 0.6545095 ,
         0.500001  , 0.9045091 , 0.7938935 , 0.6545095 , 0.500001  ,
         0.9045091 , 0.7938935 , 0.6545095 , 0.500001  , 0.9045091 ,
         0.7938935 , 0.6545095 , 0.500001  , 0.3454925 , 0.2061082 ,
         0.09549212, 0.02447206, 0.        , 0.02447143, 0.0954909 ],
        [0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 ,
         0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 ,
         0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 ,
         0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 ,
         0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 ,
         0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 ,
         0.7033674 , 0.5522632 , 0.3960431 , 0.7033674 , 0.5522632 ,
         0.3960431 , 0.7033674 , 0.5522632 , 0.3960431 , 0.7938935 ,
         0.6545095 , 0.500001  , 0.3454925 , 0.7938935 , 0.6545095 ,
         0.500001  , 0.3454925 , 0.7938935 , 0.6545095 , 0.500001  ,
         0.3454925 , 0.7938935 , 0.6545095 , 0.500001  , 0.3454925 ,
         0.7938935 , 0.6545095 , 0.500001  , 0.3454925 , 0.7938935 ,
         0.6545095 , 0.500001  , 0.3454925 , 0.2061082 , 0.09549212,
         0.02447206, 0.        , 0.02447143, 0.09549087, 0.2061065 ],
        [0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 ,
         0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 ,
         0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 ,
         0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 ,
         0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 ,
         0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 ,
         0.5522632 , 0.3960431 , 0.2499991 , 0.5522632 , 0.3960431 ,
         0.2499991 , 0.5522632 , 0.3960431 , 0.2499991 , 0.6545095 ,
         0.5000011 , 0.3454925 , 0.2061082 , 0.6545095 , 0.5000011 ,
         0.3454925 , 0.2061082 , 0.6545095 , 0.5000011 , 0.3454925 ,
         0.2061082 , 0.6545095 , 0.5000011 , 0.3454925 , 0.2061082 ,
         0.6545095 , 0.5000011 , 0.3454925 , 0.2061082 , 0.6545095 ,
         0.5000011 , 0.3454925 , 0.2061082 , 0.09549212, 0.02447206,
         0.        , 0.02447143, 0.0954909 , 0.2061065 , 0.3454905 ],
        [0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 ,
         0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 ,
         0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 ,
         0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 ,
         0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 ,
         0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 ,
         0.3960431 , 0.2499991 , 0.1284269 , 0.3960431 , 0.2499991 ,
         0.1284269 , 0.3960431 , 0.2499991 , 0.1284269 , 0.5000011 ,
         0.3454925 , 0.2061082 , 0.09549209, 0.5000011 , 0.3454925 ,
         0.2061082 , 0.09549209, 0.5000011 , 0.3454925 , 0.2061082 ,
         0.09549209, 0.5000011 , 0.3454925 , 0.2061082 , 0.09549209,
         0.5000011 , 0.3454925 , 0.2061082 , 0.09549209, 0.5000011 ,
         0.3454925 , 0.2061082 , 0.09549209, 0.02447206, 0.        ,
         0.02447143, 0.0954909 , 0.2061065 , 0.3454905 , 0.499999  ],
        [0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.2499991 ,
         0.1284269 , 0.04322684, 0.2499991 , 0.1284269 , 0.04322684,
         0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.2499991 ,
         0.1284269 , 0.04322684, 0.2499991 , 0.1284269 , 0.04322684,
         0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.2499991 ,
         0.1284269 , 0.04322684, 0.2499991 , 0.1284269 , 0.04322684,
         0.2499991 , 0.1284269 , 0.04322684, 0.2499991 , 0.1284269 ,
         0.04322684, 0.2499991 , 0.1284269 , 0.04322684, 0.3454925 ,
         0.2061082 , 0.09549212, 0.02447206, 0.3454925 , 0.2061082 ,
         0.09549212, 0.02447206, 0.3454925 , 0.2061082 , 0.09549212,
         0.02447206, 0.3454925 , 0.2061082 , 0.09549212, 0.02447206,
         0.3454925 , 0.2061082 , 0.09549212, 0.02447206, 0.3454925 ,
         0.2061082 , 0.09549212, 0.02447206, 0.        , 0.02447143,
         0.0954909 , 0.2061065 , 0.3454905 , 0.499999  , 0.6545075 ],
        [0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.1654339 ,
         0.06698677, 0.01092598, 0.1654339 , 0.06698677, 0.01092598,
         0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.1654339 ,
         0.06698677, 0.01092598, 0.1654339 , 0.06698677, 0.01092598,
         0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.1654339 ,
         0.06698677, 0.01092598, 0.1654339 , 0.06698677, 0.01092598,
         0.1654339 , 0.06698677, 0.01092598, 0.1654339 , 0.06698677,
         0.01092598, 0.1654339 , 0.06698677, 0.01092598, 0.2500009 ,
         0.1284283 , 0.0432277 , 0.00273916, 0.2500009 , 0.1284283 ,
         0.0432277 , 0.00273916, 0.2500009 , 0.1284283 , 0.0432277 ,
         0.00273916, 0.2500009 , 0.1284283 , 0.0432277 , 0.00273916,
         0.2500009 , 0.1284283 , 0.0432277 , 0.00273916, 0.2500009 ,
         0.1284283 , 0.0432277 , 0.00273916, 0.01092598, 0.06698677,
         0.1654339 , 0.2966307 , 0.4477347 , 0.6039548 , 0.7499991 ],
        [0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.06698677,
         0.01092598, 0.00273916, 0.06698677, 0.01092598, 0.00273916,
         0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.06698677,
         0.01092598, 0.00273916, 0.06698677, 0.01092598, 0.00273916,
         0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.06698677,
         0.01092598, 0.00273916, 0.06698677, 0.01092598, 0.00273916,
         0.06698677, 0.01092598, 0.00273916, 0.06698677, 0.01092598,
         0.00273916, 0.06698677, 0.01092598, 0.00273916, 0.1284283 ,
         0.0432277 , 0.00273916, 0.01092598, 0.1284283 , 0.0432277 ,
         0.00273916, 0.01092598, 0.1284283 , 0.0432277 , 0.00273916,
         0.01092598, 0.1284283 , 0.0432277 , 0.00273916, 0.01092598,
         0.1284283 , 0.0432277 , 0.00273916, 0.01092598, 0.1284283 ,
         0.0432277 , 0.00273916, 0.01092598, 0.06698677, 0.1654339 ,
         0.2966307 , 0.4477347 , 0.6039549 , 0.7499991 , 0.8715718 ]
])

### Add a dimension to fit out prediciton model

In [16]:
print(test_features.shape)
test_features = np.expand_dims(test_features, axis=0)
print(test_features.shape)

(8, 85)
(1, 8, 85)


In [17]:
model.predict(test_features)

array([[0.19760081, 0.14323074, 0.10679573, 0.10203171, 0.1187281 ,
        0.16261858, 0.34634566, 0.46769774]], dtype=float32)

In [21]:
file_name = 'training_file_crashes.txt'
file = open(file_name)
print('Loading Trainingsdata from File:', file_name,'  ...')
values = np.loadtxt(file_name, dtype='float32', skiprows=1)
print('Trainingsdata points: ', values.shape[0], "\n")
#split into input and outputs
features, targets = values[:,:-output_units], values[:,number_of_features:]
print('training_input shape: ', features.shape, 'training_output shape: ', targets.shape)

Loading Trainingsdata from File: training_file_crashes.txt   ...
Trainingsdata points:  7136 

training_input shape:  (7136, 67) training_output shape:  (7136, 8)
